//! Provides Bindings for the individual commands

macro_rules! makepl {
    ($($name:ident, $val:literal),*) => {
        $(pub const $name: &str = $val;)*
    };
}

// symbols of the commands in the order they appear in the manual
#[rustfmt::skip]
makepl!(
    READ, "Z",
    MOTOR_TYPE, ":CL_motor_type",
    PHASE_CURRENT, "i",
    STANDSTILL_PHASE_CURRENT, "r",
    BLDC_PEAK_CURRENT, ":ipeak",
    BLDC_CURRENT_TIME_CONSTANT, ":itime",
    STEP_MODE, "g",
    DRIVE_ADDRESS, "m",
    MOTOR_ID, ":mt",
    LIMIT_SWITCH_BEHAVIOR, "l",
    ERROR_CORRECTION_MODE, "U",
    AUTO_CORRECTION_RECORD, "F",
    ENCODER_DIRECTION, "q",
    SWING_OUT_TIME, "O",
    MAX_ENCODER_DEVIATION, "X",
    FEED_RATE_NUMERATOR, ":feed_const_num",
    FEED_RATE_DENOMINATOR, ":feed_const_denum",
    RESET_POS_ERR, "D",
    READ_ERR_MEM, "E",
    READ_ENCODER_POS, "I",
    READ_POS, "C",
    IS_REFERENCED, ":is_referenced",
    READ_STATUS, "$",
    READ_FIRMWARE_VERSION, "v",
    READ_OPERATING_TIME, ":optime",
    DIGITAL_INPUT_FUNCTION_PARTIAL, ":port_in_",
    DIGITAL_OUTPUT_FUNCTION_PARTIAL, ":port_out_",
    REVERSE_IN_OUT_POLARITY, "h",
    INPUT_DEBOUNCE_TIME, "K",
    OUTPUTS, "Y",
    READ_EEPROM_BYTE, "(E",
    RESET_EEPROM, "~",
    AUTO_STATUS_SENDING, "J",
    START_BOOTLOADER, "@S",
    REVERSE_CLEARANCE, "z",
    RAMP_TYPE, ":ramp_mode",
    WAIT_TIME_BRAKE_VOLTAGE_OFF, ":brake_ta",
    WAIT_TIME_MOTOR_MOVE, ":brake_tb",
    WAIT_TIME_MOTOR_CURRENT_OFF, ":brake_tc",
    BAUD_RATE, ":baud",
    CRC_CHECKSUM, ":crc",
    HALL_CFG, ":hall_mode",
    READ_TEMP, ":temp_adc",
    QUICKSTOP_RAMP, "H",
    QUICKSTOP_RAMP_NO_CONVERSION, ":decelquick",
    GEAR_FACTOR_NUMERATOR, ":gn",
    GEAR_FACTOR_DENOMINATOR, ":gd",
    START_MOTOR, "A",
    STOP_MOTOR, "S",
    LOAD_RECORD, "y",
    READ_CURRENT_RECORD, "|",
    SAVE_RECORD, ">",
    POSITIONING_MODE, "p",
    TRAVEL_DISTANCE, "s",
    MIN_FREQUENCY, "u",
    MAX_FREQUENCY, "o",
    MAX_FREQUENCY2, "n",
    ACCEL_RAMP, "b",
    ACCEL_RAMP_NO_CONVERSION, ":accel",
    BRAKE_RAMP, "B",
    BRAKE_RAMP_NO_CONVERSION, ":decel",
    ROTATION_DIRECTION, "d",
    ROTATION_DIRECTION_CHANGE, "t",
    REPETITIONS, "W",
    RECORD_PAUSE, "P",
    CONTINUATION_RECORD, "N",
    MAX_ACCEL_JERK, ":b",
    MAX_BRAKE_JERK, ":B"
);
